import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed bottom-6 right-6 flex flex-col gap-3 z-50">
          <button className="bg-blue-600 text-white px-5 py-3 rounded-full shadow-lg hover:bg-blue-700">
            📞 Talk to Expert
          </button>

          <button className="bg-green-500 text-white px-5 py-3 rounded-full shadow-lg hover:bg-green-600">
            💬 Chat with Us
          </button>
        </div>

      </body>
    </html>
  );
}
